/**
 * This class is automatically generated by ncg. DO NOT EDIT THIS FILE.
 * This class includes values of some nesC constants from
 * ../Oscilloscope.h.
 */

public class Constants  {
    public static final byte NREADINGS = 2;
    public static final byte DEFAULT_INTERVAL = 5;
}
